version: '3.9'

services:
  streamlit:
    build: ./app
    ports:
      - "8501:8501"
    depends_on:
      - ollama

  ollama:
    image: ollama/ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    tty: true
    command: >
      bash -c "
      ollama serve &
      sleep 5 &&
      ollama pull llama3 &&
      tail -f /dev/null
      "

volumes:
  ollama_data:
